title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://sharpgdx.com
logo: "/assets/images/sharpgdx-h.png"
nav_enabled: true
enable_copy_code_button: true
footer_content: "Copyright &copy; 2024 SharpGDX."
color_scheme: dark